-- MySQL Workbench Synchronization
-- Generated: 2017-12-26 11:00
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Diamond

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `cms` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `cms`.`c_article` (
  `id` VARCHAR(40) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `summary` VARCHAR(300) NULL DEFAULT NULL COMMENT '文章摘要',
  `status` INT(1) NOT NULL DEFAULT 1 COMMENT '0: 删除状态\n1: 草稿状态\n2: 发布状态',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `catalog_id` VARCHAR(40) NULL DEFAULT NULL,
  `banner` VARCHAR(150) NULL DEFAULT NULL,
  `tag_names` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_catalog` (
  `id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `sort` INT(11) NOT NULL DEFAULT 1,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_user` (
  `id` VARCHAR(40) NOT NULL,
  `username` VARCHAR(80) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `expired` BIGINT(20) NULL DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_e4ylw9v9nhrb2rjvy09b1y7xs` (`username` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_tag` (
  `id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_article_tag` (
  `article_id` VARCHAR(40) NOT NULL,
  `tag_id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`article_id`, `tag_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_page_view` (
  `id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(40) NULL DEFAULT NULL,
  `path` VARCHAR(255) NULL DEFAULT NULL,
  `params` VARCHAR(300) NULL DEFAULT NULL,
  `full_path` VARCHAR(300) NULL DEFAULT NULL,
  `query` VARCHAR(45) NULL DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_setting` (
  `id` VARCHAR(120) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '参数key',
  `value` TEXT NOT NULL,
  `type` INT(11) NOT NULL DEFAULT 1 COMMENT '1: 普通文本',
  `description` VARCHAR(140) NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_comment` (
  `id` VARCHAR(40) NOT NULL,
  `article_id` VARCHAR(40) NOT NULL,
  `nickname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `content` VARCHAR(512) NULL DEFAULT NULL,
  `state` INT(11) NOT NULL DEFAULT 1 COMMENT '0: 删除\n1: 正常\n',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip` VARCHAR(40) NOT NULL,
  `reply_id` VARCHAR(40) NULL DEFAULT NULL,
  `from_author` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_email_config` (
  `id` VARCHAR(40) NOT NULL,
  `smtp_host` VARCHAR(45) NOT NULL,
  `smtp_port` INT(11) NOT NULL,
  `ssl_enable` BIT(1) NOT NULL DEFAULT b'1' COMMENT '1: 启用\n0: 禁用',
  `email_account` VARCHAR(60) NOT NULL,
  `email_password` VARCHAR(60) NOT NULL,
  `enable` BIT(1) NOT NULL DEFAULT b'0' COMMENT '0: 禁用\n1: 启用\n是否启用配置',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_email_send` (
  `id` VARCHAR(40) NOT NULL,
  `from_email` VARCHAR(45) NOT NULL,
  `to_email` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `remark` VARCHAR(255) NULL DEFAULT NULL,
  `email_config_id` VARCHAR(40) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_keyword` (
  `id` VARCHAR(40) NOT NULL,
  `keyword` VARCHAR(80) NOT NULL,
  `ref_number` INT(11) NOT NULL DEFAULT 1,
  `full_pinyin` VARCHAR(300) NOT NULL,
  `simple_pinyin` VARCHAR(80) NOT NULL,
  `heat_number` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `keyword_UNIQUE` (`keyword` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_ip_location` (
  `ip` VARCHAR(20) NOT NULL,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `cms`.`c_guest` (
  `id` VARCHAR(40) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT now(),
  `login_time` DATETIME NOT NULL DEFAULT now(),
  `third_data` TEXT NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NULL DEFAULT NULL,
  `avatar` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
